Repository ucsb-cs156-s23/proj-gauchoride-s23-5pm-3, pull requests merged in 2023-06, with the labels that each got.

#22 Updated deployment links in README
  README.md
Labels: 5

#21 pc - update workflow 33 to publish stryker report even if coverage is below 100%
  .github/workflows/33-frontend-pr-mutation-testing.yml
Labels: staff

#24 Added DB for ride requests
  src/main/java/edu/ucsb/cs156/gauchoride/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/RideRequest.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/RideRequestRepository.java
Labels: 10

#33 Improved backend messaging
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/UsersController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/UsersControllerTests.java
Labels: 10

#34 fix frontend proxy controller
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/FrontendProxyController.java
Labels: 10

#23 Added additional roles to SecurityConfig
  src/main/java/edu/ucsb/cs156/gauchoride/config/SecurityConfig.java
Labels: 10, Merge Candidate-CI/CD

#15 added ride request form
  frontend/src/fixtures/rideRequestFixtures.js
  frontend/src/main/components/RideRequests/RideRequestForm.js
  frontend/src/stories/components/RideRequests/RideRequestForm.stories.js
  frontend/src/tests/components/RideRequests/RideRequestForm.test.js
Labels: 10

#39 pc - update workflows
  .github/workflows/10-backend-unit.yml
  .github/workflows/12-backend-jacoco.yml
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/14-backend-pitest.yml
  .github/workflows/30-frontend-tests.yml
  .github/workflows/32-frontend-coverage.yml
  .github/workflows/33-frontend-pr-mutation-testing.yml
  .github/workflows/34-frontend-main-mutation-testing.yml
  .github/workflows/36-frontend-eslint.yml
  .github/workflows/52-storybook-main-branch.yml
  .github/workflows/54-storybook-pr.yml
  .github/workflows/56-javadoc-main-branch.yml
  .github/workflows/58-javadoc-pr.yml
Labels: staff

#37 RideRequest PUT endpoint
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideRequestController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/RideRequestControllerTests.java
Labels: WONT-MERGE-S23

#40 Added Driver Shift get post endpoints
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverShiftController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/DriverShift.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/User.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/DriverShiftProjection.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/DriverShiftRepository.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverShiftControllerTests.java
Labels: 10
